version: '3'

services:  
  mysql:
    container_name: mysql
    image: library/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    networks:
      app_net:
        ipv4_address: 172.16.239.2
  goserver:
    container_name: goserver
    image: library/golang:alpine
    environment:
      - PROJECTPATH=/go/src/gomarket
    working_dir: /go/src/gomarket
    entrypoint:
      - /bin/sh
      - -c
      - |
        go build -o server
        ./server
    volumes:
      - ../:/go/src/gomarket
      - ../vendor/github.com/:/go/src/github.com/
    ports:
      - 3000:3000
    networks:
      app_net:
        ipv4_address: 172.16.239.3
    depends_on:
      - mysql
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24
